Plotcounts & more...
thomasfn/EcoCompaniesMod pull request #36
Opened 2024-08-11 11:06 UTC by silibum

This PR has the main aim to fix the plot size bug that is around a few patches long now. I removed Harmony as it blows up the binary by around 1MB and it isn't needed any more (we talked about that @thomasfn).

_Tested with a Backup of White-Tiger_

**General**
- Removed HarmonyPatches
- Updated Packages & Modkit
- prestaging workflow -> build on all branches for validation (there is a naming flaw as I left over the old name for the resulting binary-archive as "mod-binaries-staging".. please feel free to ignore this for now...)
- Misc code changes / applied some intellisense suggestions

**RefreshPlotSize & Calculation at start**
- Now uses OnPostInitialize() from Eco.Server to set correct plotcounts at serverstart
- RefreshPlotsSize() => UpdateClaimData is the new ClaimUpdate-Method

2024-08-12 14:18 UTC, thomasfn requested changes

2024-08-12 14:18 UTC, thomasfn commented on .github/workflows/prestaging.yml
> +name: build for prestatging
`prestatging` should be `prestaging`

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
> +using Eco.Server;
As per convention, this using should be in the scoped using block below as just `using Server;` (and probably in it's own paragraph)

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
> +		public bool VehicleTransfersEnabled { get; set; } = false;
Inconsistent indents, should be using spaces

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
> +                case ReputationTransfer transferTransferAction: // intercepts new reputation actions
`transferTransferAction` variable should be `reputationTransferAction`

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
> +                        Task.Delay(1000).ContinueWith((t) => // wait for ticks
Is there any particular science or reasoning to 1000ms of delay? I know I've used 250ms elsewhere to do things "later", I wonder if we should introduce a constant somewhere and make it consistent throughout the codebase

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
>          }
May as well get rid of the entire constructor now since it's not needed

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
> +        }
Incorrect bracket placement (should be on new line). Also I don't think the log message is useful beyond debugging, so it could either be removed or changed to debug category

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
>          }
Can be removed entirely

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +    using System.Threading.Tasks;
As before, usings need tidying, namely the System using goes to the top and the Eco usings trimmed and put into their correct paragraphs (yes I know the using style is weird, I wouldn't do it like this again if I rewrote all the mods from scratch but it is what it is)

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +		public static Company GetEmployer(User user)
Incorrect indenting

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +            NegativeReputationGiver ??= new();
Did you verify that `Initialize` is indeed called on every startup as well as when the company is first founded? As I say if it isn't we have some issues to sort out, but namely this would need a migration strategy for old companies that don't have these objects set. If init is called every startup this is a non-issue

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +                foreach (var targetUser in AllEmployees.Where(x => x.Name != sourceUser.Name))
Is comparing the name necessary? I thought there was a linq verb like `.Exclude` or something to exclude a certain element from the sequence, otherwise just a straight comparison of the `User` object should be fine

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +            if (!CompaniesPlugin.Obj.Config.ReputationAveragesEnabled) { return; }
I think it would be better if the legal person rep block is behind the feature flag too. So if the feature flag is off, players can still rep the legal person as before, and blocking/diverting it only happens if the feature flag is on.

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +            _reputationObj?.Relationships.Clear(); // we clear all legal person reputation to remove reputation (silent migration)
Don't need to prefix local variables with an underscore. Also other cases of this in this method

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +            Task.Delay(2500).ContinueWith((t) =>
As before with the science or reasoning about the 2500ms delay, and if it could be made consistent.

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +				reputationCountPostive = (reputationCountPostive != 0) ? reputationCountPostive / AllEmployees.Count() : reputationCountPostive;
Incorrect indenting

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +						if (ReputationManager.Obj.ReputationGivenToday(sourceUser, targetUser) != 0)
Incorrect indenting

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +                    var _newNameParts = _newName.Split(' ');
As above with underscores on local variables

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +        }
I'm not sure if I like the idea of the possibility that a company can have no CEO. If nothing else it introduces a bunch of possible NREs since everywhere always assumes a CEO exists so far. What's the reasoning behind this change?

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +            if (user == Ceo) {
Incorrect bracketing

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/CompanyCommands.cs
As before with using tidy up

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/CompanyCommands.cs
> +        public static void Status(User user)
The indenting in this file is a disaster, I won't comment on each case but it all needs normalising to use spaces. I'm not even sure I can properly read and review this diff in this state.

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/EcoCompaniesMod.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
`Fody` and `Constura` are only being used to embed the harmony assembly in the mod dll, since harmony is removed, they can go too. Also `Mono.Cecil` and `MonoMod.Common` are dependencies of harmony and can go also.

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Reputation/CompanyReputationGivers.cs
> +﻿
Remove leading empty line

2024-08-12 14:18 UTC, thomasfn commented on FodyWeavers.xml
>  		</IncludeAssemblies>
As above `Fody` is only used to embed harmony so this whole file can go away now too

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Reputation/CompanyReputationGivers.cs
> +		public LocString MarkedUpName => TextLoc.InfoLightLocStr("AVG Positive Reputation");
I think it'd be better to just say `"Average Positive Reputation"` in the name here, shortening it is ok to help code clarity but it's better to be clear with user-facing text imo.

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Reputation/CompanyReputationGivers.cs
> +#pragma warning disable CS0067
Which warning is this?

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/Reputation/CompanyReputationGivers.cs
> +	using Range = Eco.Shared.Math.Range;
Using tidy up as before (System usings to head of file, Eco usings to scoped paragraphs with prefixes trimmed).

2024-08-12 14:18 UTC, thomasfn commented on EcoCompaniesMod/CompanyManager.cs
> +		public void InterceptReputationTransfer(ReputationTransfer reputationTransferData, ref PostResult lawPostResult)
Indents need fixing as before

2024-08-12 18:50 UTC, silibum commented on EcoCompaniesMod/Company.cs
> +            NegativeReputationGiver ??= new();
Yes all cool there - what I had as we talked was through a bad migration of a save and solved after restoring the original save back.

2024-08-13 23:01 UTC, silibum commented on EcoCompaniesMod/Company.cs
> +            if (!CompaniesPlugin.Obj.Config.ReputationAveragesEnabled) { return; }
See new commit - this got a bit revamped / comments on the new variant appreciated :)

2024-08-13 23:15 UTC, silibum commented on EcoCompaniesMod/Reputation/CompanyReputationGivers.cs
> +#pragma warning disable CS0067
Outdated, I removed PropertyChanged handling entirely as it isn't needed for this "clone" of the SpeakingWellOfOthersReputationGiver

2024-08-13 23:17 UTC, silibum commented on EcoCompaniesMod/Reputation/CompanyReputationGivers.cs
> +		public LocString MarkedUpName => TextLoc.InfoLightLocStr("AVG Positive Reputation");
![image](https://github.com/user-attachments/assets/f720367a-ebfe-49ff-9f70-f2345af80b96)

Played around on that a bit and changed to a more colored version including "Employee" instead of "Positive/Negative" to make it more clear and visual.

2024-08-13 23:18 UTC, silibum commented on EcoCompaniesMod/CompaniesPlugin.cs
> +                        Task.Delay(1000).ContinueWith((t) => // wait for ticks
The long delays where for me to debug. I made it constant to 250 for all tasks now per constant.

2024-08-13 23:20 UTC, silibum commented on EcoCompaniesMod/Company.cs
> +                foreach (var targetUser in AllEmployees.Where(x => x.Name != sourceUser.Name))
This is now handled as `.Except(sourceUser.SingleItemAsEnumerable())` as `.Except` needs it as Enumerable this works and no more name compare (which indeed was bit to detailed here)

2024-08-13 23:24 UTC, silibum commented on EcoCompaniesMod/Company.cs
> +        }
I checked that and could not see any NREs we would create it beside this is more for debugging.
Most calls/uses of the CEO are `!= null` or links that are generated by `UILinkNullSafe()` or when not in the new company creation logic where we will have one...

2024-08-27 22:20 UTC, thomasfn requested changes

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
> +		[LocDescription("If enabled, the company members can't give reputation to each other nor the legal person (also counts for invited members)."), Category("Reputation")]
Indenting

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
> +        public bool ReputationAveragesBonusEnabled { get; set; } = true;
Are the default reputation settings set in a way that is best for WT?

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
> +        private static readonly Dictionary<Type, GameValueType> gameValueTypeCache = new();
I assume we can't initialise with `[]` as that's .net 8?

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyCommands.cs
> +            user.Player?.OpenInfoPanel($"Plugin-Status", sb.ToString(), "pluginSettingsInfo");
Is it possible to get a screenshot of how this looks?

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyCommands.cs
> +            } else
`else` should be on a new line from the `}`

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyCommands.cs
> +                user.OkBoxLoc($"You are already bounded to {company.UILink()}...");
Would prefer "You are an employee of X." Assuming that someone who is an employee can't be invited and joining a company will cancel all other invites?

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyCommands.cs
> +                        sb.AppendLineLoc($"Your are invite to these companies:\n\n");
Would prefer "You have invites from the following companies:"

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyCommands.cs
> +                sb.AppendLineLoc($"Your aren't invited any company.") ;
Would prefer "You have no pending invites."

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyCommands.cs
> +            user.Msg(sb.ToLocString());
Would this be better to use the transaction log ui instead? e.g. the one you get when you open your bank account's transaction history or use `/tax card`

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyManager.cs
> +			}
indenting

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyManager.cs
> +                var senderCompany     = Company.GetEmployer(reputationTransferData.ReputationSender);
Space between variable and assignment

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyManager.cs
> +                                }
indenting

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/CompanyManager.cs
> +                        Task.Delay(CompaniesPlugin.TaskDelay).ContinueWith(t => company.TakeClaim(placeOrPickUpObject.Citizen, placeOrPickUpObject.ActionLocation.XZ)); // take claimstake over if it i
Is there any particular reason there are two delayed tasks here rather than a single one that calls both?

2024-08-27 22:20 UTC, thomasfn commented on EcoCompaniesMod/Reputation/CompanyReputationGivers.cs
> +}
Indents in this file need changing to spaces

2024-08-27 22:24 UTC, silibum commented on EcoCompaniesMod/CompanyCommands.cs
> +            user.Player?.OpenInfoPanel($"Plugin-Status", sb.ToString(), "pluginSettingsInfo");
Sure: ![image](https://github.com/user-attachments/assets/e1e05c6d-004d-4a93-80be-7a5a9fa39d7e)

2024-08-27 22:37 UTC, silibum commented on EcoCompaniesMod/CompanyManager.cs
> +                        Task.Delay(CompaniesPlugin.TaskDelay).ContinueWith(t => company.TakeClaim(placeOrPickUpObject.Citizen, placeOrPickUpObject.ActionLocation.XZ)); // take claimstake over if it i
Yes I decided to seperate them as I don't want all actions to fail if something in that new operation is causing a unexpected NRE or something else. There is also a UpdateAllAuthLists() missing which I just added.

2024-08-27 22:50 UTC, silibum commented on EcoCompaniesMod/CompaniesPlugin.cs
> +        private static readonly Dictionary<Type, GameValueType> gameValueTypeCache = new();
I just applied [IDE0090 ](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0090) - made sense to me to shorten this.

2024-08-27 22:54 UTC, silibum commented on EcoCompaniesMod/CompanyCommands.cs
> +            user.Msg(sb.ToLocString());
Chat stays in backlog while the dialog closes by any UI-Click outside of it -> I think it's better to go with the chat here.

2024-08-27 22:56 UTC, silibum commented on EcoCompaniesMod/CompanyCommands.cs
> +                user.OkBoxLoc($"You are already bounded to {company.UILink()}...");
I don't understand the assumption but I try: This message is if some tries to list his invites and is already employed.
You can be invited to as many companies as you like - at the moment you accept any invite you can't list them anymore as you are now employed. That hasn't changed just the list is new - maybe a good addition to clean all invitelist but this can go in a later code iteration.

Texts is changed.

2024-08-27 23:12 UTC, thomasfn commented on EcoCompaniesMod/CompaniesPlugin.cs
> +        private static readonly Dictionary<Type, GameValueType> gameValueTypeCache = new();
Yeah don't worry about it, I'm just already used to doing `Dictionary<X, Y> z = []` but that's a .net 8 thing so we can't use it here

2024-08-27 23:17 UTC, thomasfn requested changes

2024-08-27 23:17 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +			target.MailLoc($"{headerText}\n\n{acceptLink}\n{rejectLink}", NotificationCategory.Government);
indent

2024-08-27 23:17 UTC, thomasfn commented on EcoCompaniesMod/Company.cs
> +            ignoreOwnerChanged = false;  // Okay, we're done.
Could this be wrapped in a try finally block, on the off-chance that something in there throws? e.g.

```C#
try
{
  ignoreOwnerChanged = true;
  // do stuff
}
finally
{
  ignoreOwnerChanged = false;
}
```

2024-08-27 23:17 UTC, thomasfn commented on EcoCompaniesMod/CompanyCommands.cs
> +            user.Player?.OpenInfoPanel($"Plugin-Status", sb.ToString(), "pluginSettingsInfo");
I think I'd rather the title of the UI be "Companies Mod Status" rather than "Plugin-Status" since it's not exactly clear to which plugin it refers at a glance

2024-08-27 23:31 UTC, silibum commented on EcoCompaniesMod/Company.cs
> +            ignoreOwnerChanged = false;  // Okay, we're done.
Totaly like that. Never thought that way - nice hint!

2024-08-29 03:02 UTC, thomasfn approved these changes

2024-08-29 03:02 UTC, merged